name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: 
          echo "The job ID is $GITHUB_JOB"   
          echo "The name of the event triggered by the workflow is $GITHUB_EVENT_NAME"  
          echo "The name of the workflow is $GITHUB_WORKFLOW" 
          echo "The runner of the workflow is $RUNNER_OS"
