name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: 
          echo "The job ID is $GITHUB_JOB"   
            "The name of the event triggered by the workflow is $GITHUB_EVENT_NAME"  
            "The name of the workflow is $GITHUB_WORKFLOW" 
            "The runner of the workflow is $RUNNER_OS"
      - name: Encrypted
        with: 
              secret: ${{ secrets.ANTONSECRET }}
      - name: Step with a secret
        run:
           echo "This is a secret value:${{ secrets.ANTONSECRET }}"
